// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU3SzH_FLNbxuVvF2fzZrFZ66fVacQ7gc',
    appId: '1:1021976487039:web:ecfc4cc21f2a7556d08b4a',
    messagingSenderId: '1021976487039',
    projectId: 'octogoat',
    authDomain: 'octogoat.firebaseapp.com',
    storageBucket: 'octogoat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArIeqbTgj3MDetlD-hL6egxgc8GR_N3vY',
    appId: '1:1021976487039:android:8669db3010f45a76d08b4a',
    messagingSenderId: '1021976487039',
    projectId: 'octogoat',
    storageBucket: 'octogoat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd9hSs7BKA2hfSzfF0kzFytS00s1LbZNU',
    appId: '1:1021976487039:ios:245f64129942b56bd08b4a',
    messagingSenderId: '1021976487039',
    projectId: 'octogoat',
    storageBucket: 'octogoat.appspot.com',
    iosBundleId: 'com.example.octogoat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd9hSs7BKA2hfSzfF0kzFytS00s1LbZNU',
    appId: '1:1021976487039:ios:245f64129942b56bd08b4a',
    messagingSenderId: '1021976487039',
    projectId: 'octogoat',
    storageBucket: 'octogoat.appspot.com',
    iosBundleId: 'com.example.octogoat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU3SzH_FLNbxuVvF2fzZrFZ66fVacQ7gc',
    appId: '1:1021976487039:web:e7bc39227659882bd08b4a',
    messagingSenderId: '1021976487039',
    projectId: 'octogoat',
    authDomain: 'octogoat.firebaseapp.com',
    storageBucket: 'octogoat.appspot.com',
  );
}
